[supervisord]
nodaemon=true

[program:cupsd]
command=/usr/local/bin/cupsd-run.sh
autostart=true
autorestart=true

[program:savapage-cups-notifier]
command=/opt/savapage/providers/cups/linux-x64/roottasks
autostart=true
autorestart=true
user=root

[program:savapage]
command=/usr/local/bin/savapage-run.sh
autostart=true
autorestart=true
user=savapage
